name: Continuous Delivery

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Echo
      run: echo 'Running Continuous Delivery Now'
