name: Continuous Integration

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Echo
      run: echo 'Running Continuous Integration Now'

    - name: Echo(main branch)
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo 'Only main text'

    - name: yarn version
      run: yarn --version
